set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh
set-option -g status on
set-option -g status-interval 1
set-option -g status-justify centre
set-option -g status-left '#[fg=green]#H'
set-option -g status-right '#[fg=yellow]%d %b %R'
set-option -g update-environment "DISPLAY WAYLAND_DISPLAY SSH_AUTH_SOCK XDG_RUNTIME_DIR"

bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R
bind m display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | fzf --reverse | xargs tmux switch-client -t"

bind -n M-H previous-window
bind -n M-L next-window

bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."
set -g mouse on
set -g status-keys vi
setw -g mode-keys vi
set-window-option -g pane-base-index 1

bind '&' select-window -t 1
bind 'é' select-window -t 2
bind '"' select-window -t 3
bind "'" select-window -t 4
bind '(' select-window -t 5
bind '-' select-window -t 6
bind 'è' select-window -t 7
bind '_' select-window -t 8
bind 'ç' select-window -t 9
bind 'à' select-window -t 10

bind X confirm-before -p "kill-window #W? (y/n)" kill-window
bind B switch-client -p
bind F switch-client -n
bind Tab switch-client -l

bind t run-shell 'tmux rename-window -t 1 "main💻"; \
                  tmux new-window -t 2 -n "exec🚀"; \
                  tmux new-window -t 3 -n "test🎯"; \
                  tmux new-window -t 9 -n "note📝"; \
                  tmux new-window -t 10 -n "edit✍";'

bind y run-shell 'tmux rename-window -t 1 "main💻"; \
                  tmux rename-window -t 2 "exec🚀"; \
                  tmux rename-window -t 3 "test🎯"; \
                  tmux rename-window -t 9 "note📝"; \
                  tmux rename-window -t 10 "edit✍";'


bind µ split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind S run-shell ' \
  SESSION="#{b:pane_current_path}"; \
  DIR="#{pane_current_path}"; \
  if ! tmux has-session -t "=$SESSION" 2>/dev/null; then \
    tmux new-session -d -s "$SESSION" -c "$DIR"; \
    tmux rename-window -t "$SESSION:1" "main💻"; \
    tmux new-window -t "$SESSION:2" -n "exec🚀" -c "$DIR"; \
    tmux new-window -t "$SESSION:3" -n "test🎯" -c "$DIR"; \
    tmux new-window -t "$SESSION:9" -n "note📝" -c "$DIR"; \
    tmux new-window -t "$SESSION:10" -n "edit✍" -c "$DIR"; \
  fi; \
  tmux switch-client -t "$SESSION"; \
'
bind K confirm kill-session

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " -#W-"
set -g @catppuccin_window_current_number "#I"

set -g @catppuccin_enable_icons '1'
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none

set -g set-titles on
set -g base-index 1
set -g pane-base-index 1

run '~/.tmux/plugins/tpm/tpm'
