# Shell variables
# Generated by 'wal'
wallpaper='/home/arthurk/.config/theme/background.jpg'

# Special
background='#05060A'
foreground='#dee8ef'
cursor='#dee8ef'

# Colors
color0='#05060A'
color1='#596F95'
color2='#7287A5'
color3='#6996D2'
color4='#8E9FB3'
color5='#9AB5D2'
color6='#AFCDE6'
color7='#dee8ef'
color8='#9ba2a7'
color9='#596F95'
color10='#7287A5'
color11='#6996D2'
color12='#8E9FB3'
color13='#9AB5D2'
color14='#AFCDE6'
color15='#dee8ef'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
