name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: docker-environment
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kleinarthu/docker-config:latest
    - name: Login to docker registry
      run: docker login -u kleinarthu -p ${{ env.DOCKER_TOKEN }}$
    - name: Publish new image
      run: docker push kleinarthu/docker-config:latest
